import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { CONTACT_INFO } from '../config/apiConfig';

declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
    lastAutoTable: { finalY: number };
  }
}

interface PDFData {
  id: string;
  formType?: string;
  [key: string]: any;
}

const FORM_TYPE_LABELS: Record<string, string> = {
  germany: 'ویزای آلمان',
  italy: 'ویزای ایتالیا',
  france: 'ویزای فرانسه',
  switzerland: 'ویزای سوئیس',
  canada: 'ویزای کانادا',
  australia: 'ویزای استرالیا',
  appointment: 'قرار ملاقات',
  emergency: 'درخواست اضطراری',
  multistep: 'فرم درخواست خدمات',
};

const FORM_TYPE_FILENAMES: Record<string, string> = {
  germany: 'Visa_Application',
  italy: 'Visa_Application',
  france: 'Visa_Application',
  switzerland: 'Visa_Application',
  canada: 'Visa_Application',
  australia: 'Visa_Application',
  appointment: 'Appointment',
  emergency: 'Emergency',
  multistep: 'Application',
};

export function generateApplicationPDF(data: PDFData): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  }) as any;

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPos = 20;

  // Header with gradient effect
  doc.setFillColor(26, 42, 67); // Navy color
  doc.rect(0, 0, pageWidth, 45, 'F');

  // Company name in English
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('Meta Online Service', pageWidth / 2, 15, { align: 'center' });

  // Document title
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  const formLabel = FORM_TYPE_LABELS[data.formType || 'multistep'] || 'Application';
  doc.text(`Application Confirmation - ${formLabel}`, pageWidth / 2, 25, { align: 'center' });

  // Persian subtitle (rendered as text for RTL)
  doc.setFontSize(10);
  doc.text('خدمات آنلاین میتا', pageWidth / 2, 35, { align: 'center' });

  yPos = 55;

  // Application ID Box
  doc.setFillColor(240, 244, 248);
  doc.roundedRect(15, yPos, pageWidth - 30, 20, 3, 3, 'F');
  doc.setFontSize(11);
  doc.setTextColor(26, 42, 67);
  doc.setFont('helvetica', 'bold');
  doc.text(`Application ID: ${data.id}`, pageWidth / 2, yPos + 8, { align: 'center' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  const date = new Date().toLocaleDateString('fa-IR') + ' - ' + new Date().toLocaleDateString('en-US');
  doc.text(`Date: ${date}`, pageWidth / 2, yPos + 15, { align: 'center' });
  yPos += 30;

  // Form Type Badge
  doc.setFillColor(34, 197, 94); // Emerald
  doc.roundedRect(pageWidth / 2 - 30, yPos, 60, 10, 2, 2, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.text(formLabel, pageWidth / 2, yPos + 6.5, { align: 'center' });
  yPos += 20;

  // Applicant Information Table
  doc.autoTable({
    startY: yPos,
    head: [['Field', 'Value']],
    body: Object.entries(data)
      .filter(([key]) => !['id', 'formType', 'status', 'created_at'].includes(key))
      .map(([key, value]) => {
        const formattedKey = formatFieldName(key);
        const formattedValue = formatValue(value);
        return [formattedKey, formattedValue];
      }),
    theme: 'grid',
    headStyles: {
      fillColor: [26, 42, 67],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 10,
      halign: 'center',
    },
    styles: {
      fontSize: 9,
      cellPadding: 5,
      lineWidth: 0.1,
      lineColor: [200, 200, 200],
    },
    columnStyles: {
      0: { cellWidth: 55, fontStyle: 'bold' },
      1: { cellWidth: 'auto' },
    },
    margin: { left: 15, right: 15 },
    didParseCell: (data: any) => {
      // RTL alignment for values
      if (data.column.index === 1) {
        data.cell.styles.halign = 'right';
      }
    },
  });

  // Footer
  const footerY = pageHeight - 35;
  doc.setFillColor(26, 42, 67);
  doc.rect(0, footerY, pageWidth, 35, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);

  // Contact info in footer
  doc.text('Contact Information', 15, footerY + 8);
  doc.setFontSize(8);
  doc.text(`Phone: ${CONTACT_INFO.phone}`, 15, footerY + 14);
  doc.text(`Email: ${CONTACT_INFO.email}`, 15, footerY + 19);
  doc.text(`Website: ${CONTACT_INFO.website}`, 15, footerY + 24);

  // Address on right side
  doc.setFontSize(8);
  doc.text('Office Address:', pageWidth - 15, footerY + 8, { align: 'right' });
  doc.text(CONTACT_INFO.address, pageWidth - 15, footerY + 14, { align: 'right', maxWidth: 80 });

  // Footer center text
  doc.setFontSize(7);
  doc.setTextColor(200, 200, 200);
  doc.text('This document was auto-generated by Meta Online Service', pageWidth / 2, footerY + 32, { align: 'center' });

  // Generate filename based on form type
  const filePrefix = FORM_TYPE_FILENAMES[data.formType || 'multistep'] || 'Application';
  const filename = `${filePrefix}_${data.id}.pdf`;

  // Download
  doc.save(filename);
}

function formatValue(value: any): string {
  if (value === null || value === undefined || value === '') return '-';
  if (Array.isArray(value)) return value.join(', ');
  if (typeof value === 'boolean') return value ? 'Yes' : 'No';
  return String(value);
}

function formatFieldName(key: string): string {
  const labels: Record<string, string> = {
    firstName: 'First Name',
    lastName: 'Last Name',
    fatherName: "Father's Name",
    father_name: "Father's Name",
    dateOfBirth: 'Date of Birth',
    date_of_birth: 'Date of Birth',
    gender: 'Gender',
    phone: 'Phone',
    email: 'Email',
    province: 'Province',
    address: 'Address',
    passportNumber: 'Passport Number',
    passport_number: 'Passport Number',
    passportExpiry: 'Passport Expiry',
    passport_expiry: 'Passport Expiry',
    destinationCountry: 'Destination Country',
    destination_country: 'Destination Country',
    country: 'Country',
    purpose: 'Purpose',
    notes: 'Notes',
    name: 'Name',
    last_name: 'Last Name',
    whatsapp: 'WhatsApp',
    emergency_contact: 'Emergency Contact',
    q1_security: 'Security Problems',
    q2_prior: 'Prior Filings',
    q3_proof: 'Proof Files Available',
    q4_budget: 'Transit Budget',
    q5_validity: 'Passport Validity',
    awareness: 'Awareness Source',
    awarenessSource: 'Awareness Source',
    legal_docs: 'Legal Documents',
    legalDocs: 'Legal Documents',
    case_type: 'Case Type',
    caseType: 'Case Type',
    family_count: 'Family Count',
    familyCount: 'Family Count',
    preferred_date: 'Preferred Date',
    preferred_time: 'Preferred Time',
    preferredDate: 'Preferred Date',
    preferredTime: 'Preferred Time',
    emergency_type: 'Emergency Type',
    emergencyType: 'Emergency Type',
    location: 'Location',
    description: 'Description',
    message: 'Message',
    first_name: 'First Name',
    form_type: 'Form Type',
    appointment_date: 'Appointment Date',
    passport: 'Passport',
  };
  return labels[key] || key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
}
